### PR TITLE
Feature atk articles index

### PR DESCRIPTION
**Pull request by mirdathebirda**

### CODE REVIEW

**Review by jaslakson — APPROVED** [review]

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Comment by atk-dm** [comment]
:rocket: PR was released in `v1.3.0` :rocket:

**Pull request merged**
